name = "CatTech 2"
author = "zocat"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05d7ed7bf53b8cce77be21d84d81a03ceb61da2f8a79479196a78c945b554b5f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
