name = "CatTech 2"
author = "zocat"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf0f841a987e0111fe5a80973bad1571cac65ef4b075cf454527e235c339f746"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
