name = "CatTech 2"
author = "zocat"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aa732b78b55c75ce8ada50ff50dfe250f11c340a63300751060c3ad48a3317b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
