name = "CatTech 2"
author = "zocat"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc2de828fd505657742359fb0cb5de61f3004ccfbea947baa165e481d00b2314"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
