name = "CatTech 2"
author = "zocat"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bc708b5460535b7ac690727a317a8d94cb9f15ba31f3999387c82f56b26b77f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
