name = "CatTech 2"
author = "zocat"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3b99fc319d4ce51389b7578dc548fa42e77a735aa0c39c044690e074b904174"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
